# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secman < Formula
  desc "👊 Human-friendly and amazing TUI secrets manager"
  homepage "https://secman.dev"
  version "6.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_macos_v6.2.3_arm64.zip"
      sha256 "a7771462fc0bbfb391ea1ac8b00954262aa34ba395cf6c74819d4c3d7dd92b03"

      def install
        bin.install "bin/secman"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_macos_v6.2.3_amd64.zip"
      sha256 "8d38176ab01da94cac3accdf33c41b3fd314f1f172dc24e3b790d207e8f51934"

      def install
        bin.install "bin/secman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_linux_v6.2.3_arm.zip"
      sha256 "abfd666969f4ebc28e4c5d2f96fc3acd595b09ca32c9ad6612a4fc58cf578c5f"

      def install
        bin.install "bin/secman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_linux_v6.2.3_arm64.zip"
      sha256 "158f5c07b9cfcc89ca520ce7ffe5aef992805fc4686b6e85b552751b72e74c3a"

      def install
        bin.install "bin/secman"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_linux_v6.2.3_amd64.zip"
      sha256 "cc5f3869a5376745c523afbd09cf9053cea57e650edd32bdecacd1139d8bd0b1"

      def install
        bin.install "bin/secman"
      end
    end
  end

  def post_install
    system "npm install --global @secman/scc"
  end
end
