# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secman < Formula
  desc "👊 Human-friendly and amazing TUI secrets manager"
  homepage "https://secman.dev"
  version "6.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_macos_v6.2.3_amd64.zip"
      sha256 "48fd6d57d2a495fd00d856c64f9589f9bd2bf812b475469af32da38b49390b4e"

      def install
        bin.install "bin/secman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_macos_v6.2.3_arm64.zip"
      sha256 "8854f5056028fd7640a07b5045ced0c57674dd01053a89443bb2b4aaab52d003"

      def install
        bin.install "bin/secman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_linux_v6.2.3_amd64.zip"
      sha256 "5bdecb3ad2fce449d9182cb732098fd058a086fdf2e5e2d1a55d686695a7def5"

      def install
        bin.install "bin/secman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_linux_v6.2.3_arm64.zip"
      sha256 "4d965762187a1cac4b2b36c7b7f113cbd2472b342375090b4e9bdab30a878ce2"

      def install
        bin.install "bin/secman"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/scmn-dev/secman/releases/download/v6.2.3/secman_linux_v6.2.3_arm.zip"
      sha256 "98e4cf8755f1e13ac560f62cc37a51432643f466ff392a9dce27cd741cead2db"

      def install
        bin.install "bin/secman"
      end
    end
  end

  def post_install
    system "npm install --global @secman/scc"
  end
end
