# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secman < Formula
  desc "👊 Human-friendly and amazing TUI secrets manager"
  homepage "https://secman.dev"
  version "6.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scmn-dev/secman/releases/download/v6.3.0/secman_macos_v6.3.0_amd64.zip"
      sha256 "7b86bbff158b1dc1d755ee6e6e158ae21939f156e634986f57ed8b0aaed000bc"

      def install
        bin.install "bin/secman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scmn-dev/secman/releases/download/v6.3.0/secman_macos_v6.3.0_arm64.zip"
      sha256 "cf9703d5ffd26de1a4927d2894e1fb23a4a7ca5e68c43e523e5abca9e6d5c41c"

      def install
        bin.install "bin/secman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/scmn-dev/secman/releases/download/v6.3.0/secman_linux_v6.3.0_arm.zip"
      sha256 "faf5c8fbfe1d821fb5086ab53c4841eb3cc2e180e231d0bad54e2061ab14f2c8"

      def install
        bin.install "bin/secman"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/scmn-dev/secman/releases/download/v6.3.0/secman_linux_v6.3.0_amd64.zip"
      sha256 "cee8783a78b372f9439df4b678897b7e288dc913a66caf9451cf805a89130e69"

      def install
        bin.install "bin/secman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scmn-dev/secman/releases/download/v6.3.0/secman_linux_v6.3.0_arm64.zip"
      sha256 "b5f4786d907f3f42b6029eb063e42a17d3d974426846647508f45170ffb2cf4e"

      def install
        bin.install "bin/secman"
      end
    end
  end

  def post_install
    system "npm install --global @secman/scc"
  end
end
